In [1]:
import pygrib

In [2]:
grib_name = 'oiv2mon.202012.grb'
grib_data = pygrib.open(grib_name)

In [3]:
for var in grib_data:
    print(var)
    # print(var.name)

1:Temperature:K (avgua):regular_ll:surface:level 0:fcst time 0 days (avgua):from 202012010000
2:Ice cover (1=ice, 0=no ice):(0 - 1) (avgua):regular_ll:surface:level 0:fcst time 0 days (avgua):from 202012010000


In [4]:
sst_dset = grib_data.select(name="Ice cover (1=ice, 0=no ice)")[0]
grib_data.close()
print(type(sst_dset))

<class 'pygrib._pygrib.gribmessage'>


In [5]:
sst = sst_dset.values

In [6]:
print(type(sst))

<class 'numpy.ma.core.MaskedArray'>


In [7]:
print(sst.shape)

(180, 360)


In [8]:
lats, lons = sst_dset.latlons()

In [9]:
print(lats)

[[ 89.5  89.5  89.5 ...  89.5  89.5  89.5]
 [ 88.5  88.5  88.5 ...  88.5  88.5  88.5]
 [ 87.5  87.5  87.5 ...  87.5  87.5  87.5]
 ...
 [-87.5 -87.5 -87.5 ... -87.5 -87.5 -87.5]
 [-88.5 -88.5 -88.5 ... -88.5 -88.5 -88.5]
 [-89.5 -89.5 -89.5 ... -89.5 -89.5 -89.5]]


In [10]:
print(lons)

[[  0.5   1.5   2.5 ... 357.5 358.5 359.5]
 [  0.5   1.5   2.5 ... 357.5 358.5 359.5]
 [  0.5   1.5   2.5 ... 357.5 358.5 359.5]
 ...
 [  0.5   1.5   2.5 ... 357.5 358.5 359.5]
 [  0.5   1.5   2.5 ... 357.5 358.5 359.5]
 [  0.5   1.5   2.5 ... 357.5 358.5 359.5]]
